### PR TITLE
Update for leaderboard export to include more info.

### LINKED ISSUE #183: Pull more reportback info into gladiator
potentially helpful things
- reportback item `caption`
- `why_participated`

### PR DESCRIPTION
**Pull request by weerd**
#### What's this PR do?
This PR updates the leaderboard CSV export to append a couple more data points. It adds the "why participated" data as well as the "caption" for the **latest** reportback item submitted.

#### How should this be manually tested?
Export a leaderboard and see if you see the 2 additional columns with data. 🔢 

#### Any background context you want to provide?
Nope.

#### What are the relevant tickets?
Fixes #183

---
@DoSomething/gladiator

### CODE REVIEW

**Comment by angaither** [comment]
👍

**Comment by deadlybutter** [comment]
dumb question

**Comment by deadlybutter** [comment]
what if there are no reportback items?

**Comment by weerd** [comment]
If a Reportback exists, that means there's at least always 1 reportback item.

**Comment by deadlybutter** [comment]
im just going to pretend i didnt ask that 👍

**Pull request merged**
