### PR TITLE
Adding npm install and gulp to deploy

### PR DESCRIPTION
**Pull request by blisteringherb**
#### What's this PR do?
This adds npm install and gulp to the Cap deploy

#### How should this be manually tested?
Deploy this branch to QA via Wercker

#### Any background context you want to provide?
Nothing

### CODE REVIEW

**Comment by DFurnes** [comment]
You shouldn’t need to do this, since Wercker uses the assets built during the `build` step for the `deploy` environment, and Capistrano deploys those. Hence why we don’t re-run `composer install` on Capistrano deploys either (or do this on any other Wercker-deployed apps).

**Comment by DFurnes** [comment]
Er, well follow-up – we should add these to the Wercker build step [like we do elsewhere](https://github.com/DoSomething/aurora/blob/5441fb4906acf9686c01f7d97daaae64507bef1a/wercker.yml#L14-L23) since they're not set up in this app. That way we can build and test a fully-functioning environment & the deploy only needs to be concerned with things that would happen on an application server.

**Comment by blisteringherb** [comment]
Because this app requires npm 2, I'll need to update the box that it runs on, so I'm working on that now.

**Comment by blisteringherb** [comment]
I've updated the build box and the version. Gulp and npm install seem to be working now. @angaither

**Comment by angaither** [comment]
:+1:

**Pull request merged**
