### PR TITLE
Fixes welcome emails not including first name

### LINKED ISSUE #270: Welcome email not pulling in first name token properly
image

image

All other tokens seem to be working properly for that email.

This token also appears to be working for other emails.

### PR DESCRIPTION
**Pull request by deadlybutter**
#### What's this PR do?
Fixes welcome emails not including first name

#### How should this be manually tested?
https://github.com/DoSomething/gladiator/issues/270#issuecomment-215497286

#### Any background context you want to provide?
the $account has held all of the relevant variables this entire time!

#### What are the relevant tickets?
Fixes #270

### CODE REVIEW

**Comment by weerd** [comment]
How is the leaderboard stuff related to the Welcome email?

**Comment by deadlybutter** [comment]
Its not, but Email.php tried grabbing a leaderboard & reportbacks for every email sent and not every type of email has a leaderboard or reportback attached

**Comment by deadlybutter** [comment]
Thus i was getting errors

**Comment by deadlybutter** [comment]
```
[2016-04-28 17:02:43] local.ERROR: exception 'ErrorException' with message 'Undefined property: stdClass::$reportback' in /home/vagrant/Code/gladiator/app/Services/Catalog.php:63
Stack trace:
#0 /home/vagrant/Code/gladiator/app/Services/Catalog.php(63): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(8, 'Undefined prope...', '/home/vagrant/C...', 63, Array)
#1 /home/vagrant/Code/gladiator/app/Services/Catalog.php(17): Gladiator\Services\Catalog->collateByReportbackActivity(Array)
#2 /home/vagrant/Code/gladiator/app/Services/Manager.php(105): Gladiator\Services\Catalog->build(Array, 'rank')
#3 /home/vagrant/Code/gladiator/app/Services/Email.php(164): Gladiator\Services\Manager->catalogUsers(Array)
#4 /home/vagrant/Code/gladiator/app/Services/Email.php(136): Gladiator\Services\Email->getLeaderboardVars(Array)
#5 /home/vagrant/Code/gladiator/app/Services/Email.php(58): Gladiator\Services\Email->setupEmail()
#6 /home/vagrant/Code/gladiator/app/Listeners/QueueMessage.php(36): Gladiator\Services\Email->__construct(Array)
#7 [internal function]: Gladiator\Listeners\QueueMessage->handle(Object(Gladiator\Events\QueueMessageRequest))
#8 /home/vagrant/Code/gladiator/vendor/laravel/framework/src/Illuminate/Events/CallQueuedHandler.php(43): call_user_func_array(Array, Array)
#9 /home/vagrant/Code/gladiator/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(129): Illuminate\Events\CallQueuedHandler->call(Object(Illuminate\Queue\Jobs\RedisJob), Array)
#10 /home/vagrant/Code/gladiator/vendor/laravel/framework/src/Illuminate/Queue/Jobs/RedisJob.php(50): Illuminate\Queue\Jobs\Job->resolveAndFire(Array)
#11 /home/vagrant/Code/gladiator/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(210): Illuminate\Queue\Jobs\RedisJob->fire()
#12 /home/vagrant/Code/gladiator/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(159): Illuminate\Queue\Worker->process('redis', Object(Illuminate\Queue\Jobs\RedisJob), '0', '0')
#13 /home/vagrant/Code/gladiator/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(110): Illuminate\Queue\Worker->pop('', 'default', '0', '3', '0')
#14 /home/vagrant/Code/gladiator/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(72): Illuminate\Queue\Console\WorkCommand->runWorker('', 'default', '0', '128', false)
#15 [internal function]: Illuminate\Queue\Console\WorkCommand->fire()
#16 /home/vagrant/Code/gladiator/vendor/laravel/framework/src/Illuminate/Container/Container.php(507): call_user_func_array(Array, Array)
#17 /home/vagrant/Code/gladiator/vendor/laravel/framework/src/Illuminate/Console/Command.php(169): Illuminate\Container\Container->call(Array)
#18 /home/vagrant/Code/gladiator/vendor/symfony/console/Command/Command.php(256): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#19 /home/vagrant/Code/gladiator/vendor/laravel/framework/src/Illuminate/Console/Command.php(155): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#20 /home/vagrant/Code/gladiator/vendor/symfony/console/Application.php(791): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#21 /home/vagrant/Code/gladiator/vendor/symfony/console/Application.php(186): Symfony\Component\Console\Application->doRunCommand(Object(Illuminate\Queue\Console\WorkCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#22 /home/vagrant/Code/gladiator/vendor/symfony/console/Application.php(117): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#23 /home/vagrant/Code/gladiator/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(107): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#24 /home/vagrant/Code/gladiator/artisan(36): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#25 {main}

**Comment by weerd** [comment]
Gotcha. Ok cool! And yeah, `$account` should have all the infoz ;)

**Comment by weerd** [comment]
👍

**Pull request merged**
