### PR TITLE
removes create competition button

### PR DESCRIPTION
**Pull request by deadlybutter**
#### What's this PR do?
removes the create competition button

#### How should this be manually tested?
is the button there?

#### Any background context you want to provide?
thanks fantini for pointing this out

#### What are the relevant tickets?
Fixes #no issue for this

### CODE REVIEW

**Comment by deadlybutter** [comment]
that sounds like a good idea

**Comment by deadlybutter** [comment]
removed! :tada:

**Comment by angaither** [comment]
yeah, but also the route, I think you have to say `except ['create']` 
you can still go there, and the route will fail

**Comment by deadlybutter** [comment]
ah ok

**Comment by sbsmith86** [comment]
:+1:

**Comment by angaither** [comment]
I don't know if that will mess up, if it's automatically getting created?

**Comment by deadlybutter** [comment]
@angaither why would anyone visit that route? i tried visiting locally and its just an error page saying it doesnt exist

**Comment by angaither** [comment]
@deadlybutter they shouldn't be, right?
they get created when you split the waiting room, so yeah, my first comment was right, you should add the `except` in

**Comment by deadlybutter** [comment]
@angaither gotcha, added it to the routes file

**Comment by angaither** [comment]
:+1:

**Pull request merged**
