### PR TITLE
Adding PHP League's Fractal Library for API stuff.

### LINKED ISSUE #40: Add Fractal library for API
http://fractal.thephpleague.com/ :tada: 

Refs #22
Refs #26

### PR DESCRIPTION
**Pull request by weerd**
#### What's this PR do?
Just adding the Fractal package for future API work.

#### Any background context you want to provide?
Use transformers to standardize API responses!

#### What are the relevant tickets?
Fixes #40 

---
@angaither @deadlybutter @sbsmith86 

cc: @DFurnes

### CODE REVIEW

**Comment by DFurnes** [comment]
:muscle: :computer: :soon:

**Comment by deadlybutter** [comment]
what does fractal do?

**Comment by DFurnes** [comment]
@deadlybutter http://fractal.thephpleague.com

> Fractal provides a presentation and transformation layer for complex data output, the like found in RESTful APIs, and works really well with JSON. Think of this as a view layer for your JSON/YAML/etc.

**Comment by weerd** [comment]
doh! yeah, sorry, I linked to Fractal page in issue but not in PR. Thanks @DFurnes

**Pull request merged**
