### PR TITLE
Updating api index response

### PR DESCRIPTION
**Pull request by deadlybutter**
#### What's this PR do?
Makes the default response all contests

#### How should this be manually tested?
Hit http://homestead.app/api/v1/contests/

#### Any background context you want to provide?
Blocking the cron work in Phoenix

#### What are the relevant tickets?
Fixes #NA

### CODE REVIEW

**Comment by deadlybutter** [comment]
not sure why styleci is complaining about everything again but i dont think that should block this from merging

**Comment by weerd** [comment]
No need for a transformer for the data? Or is this only temporary?

**Comment by deadlybutter** [comment]
its using the ContestTransformer thats already been built

**Comment by deadlybutter** [comment]
I can tell its working cause of the waiting room bit of the response, campaign_run":{"id":1780}},"waiting_room":{"open":true,"signup_dates":

the transformer is doin that bit

**Comment by weerd** [comment]
ah cool, ok. Yeah weird that StyleCI is complaining about all that stuff. It's all spacing related things...

**Comment by deadlybutter** [comment]
might not have updated styleci on my master, only the last feature branch

**Comment by deadlybutter** [comment]
yeah that was it, style CI is good now

**Comment by weerd** [comment]
:boom: :+1:

**Pull request merged**
