### PR TITLE
Removing the pro tip text from the default emails

### LINKED ISSUE #217: If there is no pro tip then "Pro tip - " shouldn't appear
If pro tip field is blank then we should cut the whole pro tip line all together, not have "Pro tip - " and then blank space.

image

### PR DESCRIPTION
**Pull request by deadlybutter**
#### What's this PR do?
What the title says

#### How should this be manually tested?
Does it say pro tip in the email even if there isnt a super pro tip?

#### Any background context you want to provide?
See comments in issue below

#### What are the relevant tickets?
Fixes #217

### CODE REVIEW

**Comment by angaither** [comment]
@deadlybutter let's make sure to communicate this change with Chris/Hilary since we will need to change what the current messaging is saved as already. 👍

**Comment by deadlybutter** [comment]
@angaither should we merge and then update existing stuff, or fix existing stuff then merge?

**Comment by deadlybutter** [comment]
cause i can probably fix this real quick on prod

**Comment by angaither** [comment]
@deadlybutter sure! go ahead merge and then fix

**Comment by deadlybutter** [comment]
updated

**Pull request merged**
