### PR TITLE
Updating composer packages.

### PR DESCRIPTION
**Pull request by angaither**
#### What's this PR do?
updates some stuff in `composer.json`

#### How should this be manually tested?
run `composer dump-autoload`

#### Any background context you want to provide?
I kept getting this error below, and composer update fixed it  `¯\_(ツ)_/¯ `
```
FatalErrorException in ClassLoader.php line 347:
Maximum function nesting level of '100' reached, aborting!
```

### CODE REVIEW

**Comment by sbsmith86** [comment]
the only updates are to `composer.lock`? Not `composer.json`?

**Comment by weerd** [comment]
https://laracasts.com/discuss/channels/general-discussion/l5-maximum-function-nesting-level-of-100-reached-aborting

**Comment by angaither** [comment]
@sbsmith86 oh, i guess?

**Comment by weerd** [comment]
If the `composer.json` doesn't specify an exact version but allows minor updates then that'll happen and only update the `composer.lock`.

**Comment by sbsmith86** [comment]
@weerd ah i see, i guess i don't understand why it's in version control. Maybe we all just need to run `composer update`?

**Comment by angaither** [comment]
@sbsmith86 for the [bible tells us so](https://getcomposer.org/doc/01-basic-usage.md#composer-lock-the-lock-file)

**Comment by sbsmith86** [comment]
@angaither ahhh gotcha!

**Comment by angaither** [comment]
can i get a thumbs up here or wat

**Comment by sbsmith86** [comment]
:tada:

**Pull request merged**
