### PR TITLE
Updating method names in app/helpers.php to use snake case style.

### LINKED ISSUE #163: Rename helpers.php functions using snake_case
Follows the standard Laravel sets for helper functions throughout the framework.

See discussion [here](https://github.com/DoSomething/gladiator/pull/161#issuecomment-204087216).

### PR DESCRIPTION
**Pull request by AlejandroLuperon**
#### What's this PR do?
The method names in app/helpers.php have been renamed to use snake case style.

#### Any background context you want to provide?
It is customary for helpers in laravel to use snake case style (see https://laravel.com/docs/5.1/helpers).

#### What are the relevant tickets?
Fixes #163

### CODE REVIEW

**Comment by mshmsh5000** [comment]
The specific changes look good, but won't merging this PR break all invocations of these functions?

For instance: https://github.com/DoSomething/gladiator/search?utf8=%E2%9C%93&q=buildCSV

**Comment by AlejandroLuperon** [comment]
Thank you @mshmsh5000. I will fix the errors.

**Comment by mshmsh5000** [comment]
Sounds good :beers: :fireworks: :+1:

**Comment by mshmsh5000** [comment]
The changes look good. In the future, you should have a dedicated feature branch for this work, so you're not making a PR from your fork's master (`AlejandroLuperon:master`), but instead something like `AlejandroLuperon:163-helper-names`).

**Comment by AlejandroLuperon** [comment]
Thank you! I will use feature branches moving forward.

**Pull request merged**
